// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 ReelVault Contributors

//! Full-resolution classification for indexed videos.
//!
//! A video is classified as one of:
//!
//! - [`Classification::Full`] — its recorded `(width, height)` matches a
//!   known native sensor resolution for the camera that captured it.
//!   Typical example: a timelapse rendered at the camera's full photo
//!   resolution (e.g. 6000×4000 on a Sony a7 III).
//!
//! - [`Classification::NotFull`] — the camera is known but the recorded
//!   resolution doesn't match any of its native modes *and* isn't one
//!   of the [`STANDARD_VIDEO_RESOLUTIONS`] common downscaled outputs.
//!   Typical example: a hand-exported 1500×844 clip from a known body.
//!
//! - [`Classification::Unknown`] — either we don't know the camera, or
//!   the recorded resolution is a common video standard
//!   (UHD/FHD/HD/DCI/etc.) where we can't tell in-camera downsample
//!   from post-processed export. Both end up as "no badge" in the UI.
//!
//! The classification deliberately *refuses to guess* on standard video
//! outputs — those are too ambiguous to label either way without
//! per-shot intent metadata we don't have. The trade-off, requested by
//! the user, is that some "actually full" in-camera 4K UHD clips will
//! be Unknown rather than Full. Better silent than wrong.
//!
//! ## Orientation
//!
//! Resolution matching is orientation-agnostic. A sensor that emits
//! 6000×4000 in landscape produces 4000×6000 when rotated; both match
//! the same `[6000, 4000]` table entry. The same swap is applied to
//! [`STANDARD_VIDEO_RESOLUTIONS`] — a vertical 1080×1920 clip is FHD.
//!
//! ## Data sources
//!
//! Two sources of native resolutions are merged at lookup time:
//!
//! 1. The built-in `SENSOR_RESOLUTIONS` table generated by `build.rs`
//!    from `core/data/sensor_resolutions.json`. Hand-curated; ships
//!    with the binary; covers ~150 bodies.
//! 2. The runtime cache populated by [`crate::sensor_cache`] when we
//!    encounter an unknown camera during scan. See that module for
//!    the Wikidata lookup that backs the cache.
//!
//! Built-in entries always win — if a body is in both tables, the
//! built-in resolutions are used and the runtime entries for that
//! camera are ignored. This keeps user-visible behaviour stable even
//! if Wikidata briefly returns something noisy for a body we already
//! cover.

use crate::camera_names;

// Compile-time table generated by build.rs from sensor_resolutions.json.
// Each entry is `(normalised_camera_key, &[(width, height), …])`.
include!(concat!(env!("OUT_DIR"), "/sensor_data.rs"));

/// Three-state verdict surfaced on the gRPC `VideoSummary` /
/// `VideoMetadata` messages. The `Unknown` variant covers both
/// "no camera_model known" and "recorded resolution is a common
/// video standard"; both render as "no badge" in the clients.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Classification {
    /// Recorded resolution matches the camera's native sensor.
    Full,
    /// Camera is known; recorded resolution is non-standard and
    /// non-native — likely a derived/exported version.
    NotFull,
    /// Camera unknown, or recorded resolution is a standard video
    /// output (UHD, FHD, etc.).
    Unknown,
}

/// Common video output resolutions where we deliberately decline to
/// classify. A clip at one of these could be an in-camera mode, a
/// straight downsample, or a post export — there's no way to tell
/// from `(w, h)` alone. Stored as `(width, height)` with the
/// landscape orientation; lookup checks both orientations.
///
/// Coverage spans HD/FHD, the two 4K conventions (UHD 3840×2160 and
/// DCI 4096×2160), common 5K/6K/8K cinema outputs, and a couple of
/// older formats that still show up (PAL/NTSC SD, 720p variants).
/// New formats can be added as they become common.
pub const STANDARD_VIDEO_RESOLUTIONS: &[(u32, u32)] = &[
    // SD legacy
    (640, 480),
    (720, 480),    // NTSC DV
    (720, 576),    // PAL DV
    (854, 480),
    // HD
    (1280, 720),   // HD 720p
    (1440, 1080),  // HDV 1080i
    (1920, 1080),  // FHD 1080p
    (2048, 1080),  // DCI 2K
    // 4K
    (3840, 2160),  // UHD 4K
    (4096, 2160),  // DCI 4K
    // 5K / 6K / 8K
    (5120, 2160),  // 5K wide
    (5120, 2700),  // 5K2K
    (5120, 2880),  // 5K (iMac)
    (6144, 3240),  // 6K
    (7680, 4320),  // UHD 8K
    (8192, 4320),  // DCI 8K
];

/// Pure classifier given a list of native sensor resolutions and the
/// recorded `(width, height)` of a video.
///
/// Callers normally use [`classify`] (which looks the natives up
/// itself); this lower-level form exists so the runtime cache layer
/// can merge built-in + cached natives before deciding.
///
/// `natives` may be empty — in that case any non-standard resolution
/// is `Unknown` (we can't tell whether it's full or not without a
/// reference to compare against).
pub fn classify_with_natives(natives: &[(u32, u32)], width: u32, height: u32) -> Classification {
    if width == 0 || height == 0 {
        return Classification::Unknown;
    }
    if matches_orientation_agnostic(STANDARD_VIDEO_RESOLUTIONS, width, height) {
        return Classification::Unknown;
    }
    if natives.is_empty() {
        return Classification::Unknown;
    }
    if matches_orientation_agnostic(natives, width, height) {
        Classification::Full
    } else {
        Classification::NotFull
    }
}

/// Classify using only the built-in sensor table. Equivalent to
/// `classify_with_natives(builtin_natives(camera_model), w, h)`.
pub fn classify(camera_model: &str, width: u32, height: u32) -> Classification {
    classify_with_natives(builtin_natives(camera_model), width, height)
}

/// Native sensor resolutions for `camera_model` in the built-in table,
/// or an empty slice if the camera isn't known.
///
/// The lookup is case-insensitive and whitespace-tolerant — the same
/// normalisation [`camera_names::normalise`] applies for marketing-name
/// lookups. So `"sony  ilce-7rm3"` and `"SONY ILCE-7RM3"` both resolve
/// to the same entry.
pub fn builtin_natives(camera_model: &str) -> &'static [(u32, u32)] {
    let key = camera_names::normalise(camera_model);
    if key.is_empty() {
        return &[];
    }
    for (k, v) in SENSOR_RESOLUTIONS {
        if *k == key.as_str() {
            return v;
        }
    }
    &[]
}

/// Number of camera bodies in the built-in table — handy for tests and
/// for status output (`reelvault status` shows it so users know how
/// rich the bundled coverage is).
pub fn builtin_camera_count() -> usize {
    SENSOR_RESOLUTIONS.len()
}

/// Max in-camera video recording resolution for `camera_model`, if the
/// built-in table knows one. `None` means either the camera is unknown
/// to us, or its `video_max` is intentionally null in the JSON (cinema /
/// open-gate bodies that record video at sensor native — no useful
/// timelapse signal possible).
pub fn video_max_for(camera_model: &str) -> Option<(u32, u32)> {
    let key = crate::camera_names::normalise(camera_model);
    if key.is_empty() {
        return None;
    }
    SENSOR_VIDEO_MAX
        .iter()
        .find(|(k, _)| *k == key.as_str())
        .map(|(_, v)| *v)
}

/// Decide whether a recorded clip's `(width, height)` is unreachable
/// for `camera_model`'s in-camera video pipeline, and therefore must
/// have been assembled from stills (i.e. a timelapse).
///
/// Returns `true` only when **all** of:
/// - the camera has a known `video_max`,
/// - the recorded clip's pixel area is **strictly greater** than the
///   camera's `video_max` pixel area, AND
/// - the recorded resolution matches one of the camera's sensor
///   natives (orientation-agnostic) — i.e. it's a Full-resolution
///   clip exceeding what the camera can shoot as video.
///
/// All other cases return `false`. The strict-and combined gate means:
/// - Unknown cameras → false (we don't speculate).
/// - Cameras with `video_max == null` → false (cinema bodies).
/// - Non-standard non-native resolutions exceeding video_max → false
///   (probably a custom export, not a timelapse).
/// - Clips at video_max or below → false (could be in-camera video).
///
/// The "must match a native" condition rules out false positives like
/// a 6500×3700 oddball export that happens to exceed video_max but
/// doesn't actually look like a still-photo render.
pub fn is_likely_timelapse(camera_model: &str, width: u32, height: u32) -> bool {
    if width == 0 || height == 0 {
        return false;
    }
    let Some((vw, vh)) = video_max_for(camera_model) else {
        return false;
    };
    let recorded_area = width as u64 * height as u64;
    let video_max_area = vw as u64 * vh as u64;
    if recorded_area <= video_max_area {
        return false;
    }
    let natives = builtin_natives(camera_model);
    matches_orientation_agnostic(natives, width, height)
}

fn matches_orientation_agnostic(list: &[(u32, u32)], width: u32, height: u32) -> bool {
    list.iter().any(|(w, h)| {
        (*w == width && *h == height) || (*w == height && *h == width)
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    // ----- pure classifier (no built-in table dependency) -----

    #[test]
    fn empty_dimensions_are_unknown() {
        assert_eq!(classify_with_natives(&[(6000, 4000)], 0, 0), Classification::Unknown);
        assert_eq!(classify_with_natives(&[(6000, 4000)], 0, 4000), Classification::Unknown);
        assert_eq!(classify_with_natives(&[(6000, 4000)], 6000, 0), Classification::Unknown);
    }

    #[test]
    fn standard_video_resolutions_are_always_unknown() {
        // Even with a known camera native list, a UHD clip is Unknown.
        let natives = [(6000, 4000)];
        assert_eq!(classify_with_natives(&natives, 3840, 2160), Classification::Unknown);
        assert_eq!(classify_with_natives(&natives, 1920, 1080), Classification::Unknown);
        assert_eq!(classify_with_natives(&natives, 4096, 2160), Classification::Unknown);
        assert_eq!(classify_with_natives(&natives, 7680, 4320), Classification::Unknown);
    }

    #[test]
    fn standard_video_match_is_orientation_agnostic() {
        // A portrait 1080×1920 clip is FHD too.
        assert_eq!(
            classify_with_natives(&[(6000, 4000)], 1080, 1920),
            Classification::Unknown
        );
        assert_eq!(
            classify_with_natives(&[(6000, 4000)], 2160, 3840),
            Classification::Unknown
        );
    }

    #[test]
    fn empty_natives_with_non_standard_is_unknown() {
        // No camera known + non-standard resolution -> can't classify.
        assert_eq!(classify_with_natives(&[], 1500, 844), Classification::Unknown);
    }

    #[test]
    fn match_against_natives_is_full() {
        assert_eq!(
            classify_with_natives(&[(6000, 4000)], 6000, 4000),
            Classification::Full
        );
    }

    #[test]
    fn match_against_natives_is_orientation_agnostic() {
        // Portrait orientation of the same sensor still counts as Full.
        assert_eq!(
            classify_with_natives(&[(6000, 4000)], 4000, 6000),
            Classification::Full
        );
    }

    #[test]
    fn multiple_natives_any_match_wins() {
        // S5II-style camera with photo and open-gate video modes.
        let natives = [(6000, 4000), (5952, 3968)];
        assert_eq!(classify_with_natives(&natives, 6000, 4000), Classification::Full);
        assert_eq!(classify_with_natives(&natives, 5952, 3968), Classification::Full);
        // A non-matching, non-standard size is NotFull.
        assert_eq!(classify_with_natives(&natives, 4800, 3200), Classification::NotFull);
    }

    #[test]
    fn known_camera_non_standard_non_native_is_not_full() {
        // Camera known (so natives non-empty), resolution is non-standard
        // and doesn't match -> NotFull.
        assert_eq!(
            classify_with_natives(&[(6000, 4000)], 1500, 844),
            Classification::NotFull
        );
    }

    // ----- end-to-end against the bundled table -----

    #[test]
    fn builtin_table_is_non_empty() {
        // If this fails, build.rs didn't read sensor_resolutions.json.
        assert!(builtin_camera_count() > 50,
            "expected at least 50 cameras in the built-in table; got {}",
            builtin_camera_count());
    }

    #[test]
    fn sony_a7riii_timelapse_resolves_full() {
        // 7952×5304 = the a7R III's native sensor; this is what a
        // timelapse rendered at full sensor res would land at.
        assert_eq!(
            classify("SONY ILCE-7RM3", 7952, 5304),
            Classification::Full
        );
    }

    #[test]
    fn sony_a7iii_uhd_is_unknown_not_full() {
        // The a7 III shoots 3840×2160 UHD natively; we deliberately
        // refuse to label this Full even though it's the camera's max
        // video output, because we can't tell it apart from a post
        // export to UHD. Per the user's classifier design.
        assert_eq!(
            classify("SONY ILCE-7M3", 3840, 2160),
            Classification::Unknown
        );
    }

    #[test]
    fn sony_a7iii_timelapse_is_full() {
        // But a timelapse at the sensor's photo native is clearly Full.
        assert_eq!(
            classify("SONY ILCE-7M3", 6000, 4000),
            Classification::Full
        );
        // Portrait works too.
        assert_eq!(
            classify("SONY ILCE-7M3", 4000, 6000),
            Classification::Full
        );
    }

    #[test]
    fn camera_lookup_is_case_insensitive() {
        assert_eq!(
            classify("sony ilce-7rm3", 7952, 5304),
            Classification::Full
        );
        assert_eq!(
            classify("Sony Ilce-7Rm3", 7952, 5304),
            Classification::Full
        );
    }

    #[test]
    fn unknown_camera_is_unknown() {
        assert_eq!(
            classify("HASSELBLAD UNKNOWN BODY", 8000, 6000),
            Classification::Unknown
        );
        assert_eq!(classify("", 6000, 4000), Classification::Unknown);
    }

    #[test]
    fn unknown_camera_with_standard_resolution_is_still_unknown() {
        assert_eq!(
            classify("CAMERA WE DONT HAVE", 3840, 2160),
            Classification::Unknown
        );
    }

    #[test]
    fn s5ii_open_gate_is_full() {
        // The S5 II's 6K open-gate mode (5952×3968) IS one of its
        // natives — gets the Full label.
        assert_eq!(
            classify("PANASONIC DC-S5M2", 5952, 3968),
            Classification::Full
        );
        // And the photo native, just to confirm both entries are reachable.
        assert_eq!(
            classify("PANASONIC DC-S5M2", 6000, 4000),
            Classification::Full
        );
    }

    #[test]
    fn ursa_mini_pro_12k_full() {
        assert_eq!(
            classify("BLACKMAGIC DESIGN URSA MINI PRO 12K", 12288, 6480),
            Classification::Full
        );
    }

    #[test]
    fn nikon_z8_resolves_via_short_and_long_make_prefix() {
        // Both prefixes are in the table — make sure neither one regresses.
        assert_eq!(
            classify("NIKON CORPORATION NIKON Z 8", 8256, 5504),
            Classification::Full
        );
        assert_eq!(classify("NIKON Z 8", 8256, 5504), Classification::Full);
    }

    #[test]
    fn iphone_15_pro_proraw_is_full() {
        // ProRAW at 48MP.
        assert_eq!(
            classify("APPLE IPHONE 15 PRO", 8064, 6048),
            Classification::Full
        );
        // Standard 12MP fallback also full (sensor binning to 12MP is
        // still one of the camera's native outputs).
        assert_eq!(
            classify("APPLE IPHONE 15 PRO", 4032, 3024),
            Classification::Full
        );
    }

    #[test]
    fn iphone_video_at_uhd_is_unknown() {
        // 4K video from any iPhone -> standard format, Unknown.
        assert_eq!(
            classify("APPLE IPHONE 15 PRO", 3840, 2160),
            Classification::Unknown
        );
    }

    #[test]
    fn whitespace_in_camera_name_collapses() {
        // Extra whitespace from copy-paste shouldn't break the lookup.
        assert_eq!(
            classify("  SONY  ILCE-7RM3  ", 7952, 5304),
            Classification::Full
        );
    }

    // ----- timelapse heuristic -----

    #[test]
    fn sony_a7iii_at_photo_native_is_timelapse() {
        // a7 III maxes at UHD 4K video; 6000×4000 stills exceed that.
        // Therefore a 6000×4000 video must be assembled from stills.
        assert!(is_likely_timelapse("SONY ILCE-7M3", 6000, 4000));
        // Portrait orientation too.
        assert!(is_likely_timelapse("SONY ILCE-7M3", 4000, 6000));
    }

    #[test]
    fn sony_a7iii_at_uhd_is_not_timelapse() {
        // 3840×2160 is the camera's video_max — within in-camera capability.
        assert!(!is_likely_timelapse("SONY ILCE-7M3", 3840, 2160));
    }

    #[test]
    fn unknown_camera_never_timelapse() {
        assert!(!is_likely_timelapse("HASSELBLAD UNKNOWN", 11656, 8742));
        assert!(!is_likely_timelapse("", 6000, 4000));
    }

    #[test]
    fn open_gate_camera_never_timelapse() {
        // The GH6 records open-gate video at 5776×4336 — the same as its
        // photo native. Photo-resolution video is genuinely possible
        // in-camera, so we refuse to call it a timelapse.
        assert!(!is_likely_timelapse("PANASONIC DC-GH6", 5776, 4336));
    }

    #[test]
    fn blackmagic_pocket_6k_never_timelapse() {
        // BMPCC 6K records video at sensor native. No timelapse signal.
        assert!(!is_likely_timelapse(
            "BLACKMAGIC DESIGN BMPCC6K",
            6144,
            3456
        ));
    }

    #[test]
    fn r5_8k_photo_is_timelapse() {
        // Canon R5: photo 8192×5464, max video 8192×4320 (8K DCI).
        // A 8192×5464 video exceeds 8K DCI video area, so timelapse.
        assert!(is_likely_timelapse("CANON EOS R5", 8192, 5464));
        // 8192×4320 is the in-camera 8K mode — NOT timelapse.
        assert!(!is_likely_timelapse("CANON EOS R5", 8192, 4320));
    }

    #[test]
    fn iphone_15_pro_proraw_is_timelapse() {
        // iPhone 15 Pro: 8064×6048 ProRAW photos, max video 4K UHD.
        // A 8064×6048 video from an iPhone is clearly time-stitched.
        assert!(is_likely_timelapse("APPLE IPHONE 15 PRO", 8064, 6048));
        // Standard 4032×3024 stills also exceed UHD video area.
        assert!(is_likely_timelapse("APPLE IPHONE 15 PRO", 4032, 3024));
    }

    #[test]
    fn non_native_oversized_resolution_is_not_timelapse() {
        // Some weird 9000×3000 export exceeds video_max in pixel count
        // but doesn't match any native sensor mode — so we don't call
        // it a timelapse. Avoids false positives from arbitrary
        // post-process exports.
        assert!(!is_likely_timelapse("SONY ILCE-7M3", 9000, 3000));
    }

    #[test]
    fn video_max_lookup_round_trip() {
        assert_eq!(video_max_for("SONY ILCE-7M3"), Some((3840, 2160)));
        // Cinema body: video_max intentionally null.
        assert_eq!(video_max_for("BLACKMAGIC DESIGN BMPCC6K"), Some((6144, 3456)));
        // Unknown camera.
        assert_eq!(video_max_for("HASSELBLAD X2D 100C"), None);
        // Empty string.
        assert_eq!(video_max_for(""), None);
    }
}
